// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/hibiken/asynq"
	"sili-smart-hr/backend/internal/api/handler"
	"sili-smart-hr/backend/internal/api/router"
	"sili-smart-hr/backend/internal/config"
	"sili-smart-hr/backend/internal/engine/fallback"
	"sili-smart-hr/backend/internal/engine/pipeline"
	"sili-smart-hr/backend/internal/engine/scorer"
	"sili-smart-hr/backend/internal/model"
	"sili-smart-hr/backend/internal/repository"
	"sili-smart-hr/backend/internal/service"
	"sili-smart-hr/backend/internal/worker/scheduler"
	"sili-smart-hr/backend/internal/worker/server"
)

// Injectors from wire.go:

// InitializeApp 单一 injector：config → db → redis → asynq → repository → service → handler → router。
func InitializeApp(configPath string) (*App, error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, err
	}
	manager, err := NewJWTManager(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := model.InitDB(configConfig)
	if err != nil {
		return nil, err
	}
	accountRepository := repository.NewAccountRepository(db)
	client := NewRedisClient(configConfig)
	rsakeyManager := NewRSAManager(configConfig, client)
	accountService := service.NewAccountService(accountRepository, manager, rsakeyManager)
	accountHandler := handler.NewAccountHandler(accountService, rsakeyManager)
	healthHandler := handler.NewHealthHandler()
	systemInitializationRepository := repository.NewSystemInitializationRepository(db)
	dbProbe := ProvideDBProbe(db)
	redisProbe := ProvideRedisProbe(client)
	jwtSecretSecure := NewJWTSecretSecure(configConfig)
	setupService := NewSetupServiceAdapter(db, systemInitializationRepository, accountRepository, rsakeyManager, dbProbe, redisProbe, jwtSecretSecure)
	setupHandler := handler.NewSetupHandler(setupService)
	llmConfigRepository := repository.NewLLMConfigRepository(db)
	v := NewLLMEncKey(configConfig)
	enabledModelProvider := service.NewLLMEnabledProvider(llmConfigRepository, v)
	llmClient := NewLLMClient(enabledModelProvider)
	integrationSecretRepository := repository.NewIntegrationSecretRepository(db)
	conversationlogClient := NewConversationlogClient(configConfig)
	dependencyProbe := NewRealDependencyProbeProvider(llmClient, integrationSecretRepository, v, conversationlogClient)
	systemService := NewSystemServiceAdapter(systemInitializationRepository, dbProbe, redisProbe, dependencyProbe)
	systemHandler := handler.NewSystemHandler(systemService)
	dimensionRepository := repository.NewDimensionRepository(db)
	dimensionService := service.NewDimensionService(dimensionRepository)
	dimensionHandler := handler.NewDimensionHandler(dimensionService)
	assessmentConfigRepository := repository.NewAssessmentConfigRepository(db)
	userapiClient := NewUserapiClient(configConfig)
	serviceUserapiClient := service.ProvideUserapiClient(userapiClient)
	assessmentConfigService := service.NewAssessmentConfigService(assessmentConfigRepository, serviceUserapiClient, integrationSecretRepository, v)
	assessmentConfigHandler := handler.NewAssessmentConfigHandler(assessmentConfigService)
	assessmentBatchRepository := repository.NewAssessmentBatchRepository(db)
	nowFunc := ProvideNowFunc()
	sessionFeatureRepository := repository.NewSessionFeatureRepository(db)
	evaluatorLLMClient := NewEvaluatorLLMClient(enabledModelProvider)
	dimensionSpecReaderAdapter := NewDimensionSpecReader(dimensionRepository)
	activityThresholdReader := NewActivityThresholdReader(dimensionRepository)
	dimensionScoreRepository := repository.NewDimensionScoreRepository(db)
	v2 := NewExtractorSysParamDefaults()
	systemParamReader := repository.NewSystemParamReader(db, v2)
	activityStatRepository := repository.NewActivityStatRepository(db)
	activity := NewActivityProvider(conversationlogClient, sessionFeatureRepository, activityThresholdReader, activityStatRepository, integrationSecretRepository, v)
	aggregateScoreRepository := repository.NewAggregateScoreRepository(db)
	scorerScorer := scorer.New(dimensionScoreRepository, aggregateScoreRepository)
	evaluator := NewEvaluatorProvider(evaluatorLLMClient, enabledModelProvider, sessionFeatureRepository, dimensionSpecReaderAdapter, activityThresholdReader, dimensionScoreRepository, systemParamReader, activity, scorerScorer)
	assessmentAlertRepository := repository.NewAssessmentAlertRepository(db)
	alertWriter := fallback.NewAlertWriter(assessmentAlertRepository)
	redisConnOpt := NewAsynqConnOpt(configConfig)
	asynqClient := asynq.NewClient(redisConnOpt)
	asynqEnqueuer := pipeline.NewAsynqEnqueuer(asynqClient)
	orchestrator := NewOrchestratorProvider(assessmentBatchRepository, sessionFeatureRepository, assessmentConfigRepository, conversationlogClient, userapiClient, integrationSecretRepository, v, evaluator, alertWriter, asynqEnqueuer)
	assessmentBatchService := NewAssessmentBatchServiceAdapter(assessmentBatchRepository, assessmentConfigRepository, dimensionRepository, userapiClient, integrationSecretRepository, v, nowFunc, orchestrator)
	assessmentBatchHandler := handler.NewAssessmentBatchHandler(assessmentBatchService)
	llmConfigService := service.NewLLMConfigService(llmConfigRepository, rsakeyManager, v)
	llmConfigHandler := handler.NewLLMConfigHandler(llmConfigService)
	integrationSecretService := service.NewIntegrationSecretService(integrationSecretRepository, rsakeyManager, v, conversationlogClient)
	integrationSecretHandler := handler.NewIntegrationSecretHandler(integrationSecretService)
	questionRepository := repository.NewQuestionRepository(db)
	questionService := service.NewQuestionService(questionRepository, dimensionRepository)
	questionBatchRepository := repository.NewQuestionBatchRepository(db)
	questionBatchService := service.NewQuestionBatchService(questionBatchRepository, questionRepository, dimensionRepository)
	questionHandler := handler.NewQuestionHandler(questionService, dimensionService, questionBatchService)
	questionBatchHandler := handler.NewQuestionBatchHandler(questionBatchService)
	scaleRepository := repository.NewScaleRepository(db)
	scaleService := service.NewScaleService(scaleRepository)
	scaleHandler := handler.NewScaleHandler(scaleService)
	engine := router.NewRouter(configConfig, manager, accountHandler, healthHandler, setupHandler, systemHandler, dimensionHandler, assessmentConfigHandler, assessmentBatchHandler, llmConfigHandler, integrationSecretHandler, questionHandler, questionBatchHandler, scaleHandler, client)
	httpAddr := NewHTTPAddr(configConfig)
	int2 := NewAsynqConcurrency(configConfig)
	asynqServer := server.NewServer(redisConnOpt, int2)
	extractorLLMClient := NewExtractorLLMClient(enabledModelProvider)
	extractor := NewExtractorProvider(extractorLLMClient, conversationlogClient, sessionFeatureRepository, systemParamReader, integrationSecretRepository, v)
	sessionExtractHandler := NewSessionExtractHandlerTyped(extractor)
	personEvaluateHandler := NewPersonEvaluateHandlerTyped(evaluator)
	batchTickHandler := NewBatchTickHandlerTyped(orchestrator)
	batchRunHandler := NewBatchRunHandlerTyped(orchestrator)
	questionGenLLMClient := NewQuestionGenLLMClient(enabledModelProvider)
	questionGenerationRepository := repository.NewQuestionGenerationRepository(db)
	questionDimensionSpecReader := NewQuestionDimensionSpecReader(dimensionRepository)
	generator := NewQuestionGenProvider(questionGenLLMClient, questionGenerationRepository, questionBatchRepository, questionDimensionSpecReader)
	questionGenerateHandler := NewQuestionGenerateHandlerTyped(generator)
	serveMux := NewMuxAdapter(sessionExtractHandler, personEvaluateHandler, batchTickHandler, batchRunHandler, questionGenerateHandler)
	asynqScheduler := scheduler.NewScheduler(redisConnOpt)
	app := &App{
		Config:      configConfig,
		Engine:      engine,
		HTTPAddr:    httpAddr,
		DB:          db,
		Redis:       client,
		AsynqClient: asynqClient,
		AsynqServer: asynqServer,
		Mux:         serveMux,
		Scheduler:   asynqScheduler,
	}
	return app, nil
}
