// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/hibiken/asynq"
	"sili-smart-hr/backend/internal/api/handler"
	"sili-smart-hr/backend/internal/api/router"
	"sili-smart-hr/backend/internal/config"
	"sili-smart-hr/backend/internal/engine/pipeline"
	"sili-smart-hr/backend/internal/engine/scorer"
	"sili-smart-hr/backend/internal/model"
	"sili-smart-hr/backend/internal/repository"
	"sili-smart-hr/backend/internal/service"
	"sili-smart-hr/backend/internal/worker/scheduler"
	"sili-smart-hr/backend/internal/worker/server"
)

// Injectors from wire.go:

// InitializeApp 单一 injector：config → db → redis → asynq → repository → service → handler → router。
func InitializeApp(configPath string) (*App, error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, err
	}
	manager, err := NewJWTManager(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := model.InitDB(configConfig)
	if err != nil {
		return nil, err
	}
	accountRepository := repository.NewAccountRepository(db)
	client := NewRedisClient(configConfig)
	rsakeyManager := NewRSAManager(configConfig, client)
	accountService := service.NewAccountService(accountRepository, manager, rsakeyManager)
	accountHandler := handler.NewAccountHandler(accountService, rsakeyManager)
	healthHandler := handler.NewHealthHandler()
	systemInitializationRepository := repository.NewSystemInitializationRepository(db)
	dbProbe := ProvideDBProbe(db)
	redisProbe := ProvideRedisProbe(client)
	jwtSecretSecure := NewJWTSecretSecure(configConfig)
	setupService := NewSetupServiceAdapter(db, systemInitializationRepository, accountRepository, rsakeyManager, dbProbe, redisProbe, jwtSecretSecure)
	setupHandler := handler.NewSetupHandler(setupService)
	llmConfigRepository := repository.NewLLMConfigRepository(db)
	v := NewLLMEncKey(configConfig)
	enabledModelProvider := service.NewLLMEnabledProvider(llmConfigRepository, v)
	llmClient := NewLLMClient(enabledModelProvider)
	integrationSecretRepository := repository.NewIntegrationSecretRepository(db)
	conversationlogClient := NewConversationlogClient(configConfig)
	dependencyProbe := NewRealDependencyProbeProvider(llmClient, integrationSecretRepository, v, conversationlogClient)
	systemService := NewSystemServiceAdapter(systemInitializationRepository, dbProbe, redisProbe, dependencyProbe)
	systemHandler := handler.NewSystemHandler(systemService)
	dimensionRepository := repository.NewDimensionRepository(db)
	dimensionService := service.NewDimensionService(dimensionRepository)
	dimensionHandler := handler.NewDimensionHandler(dimensionService)
	assessmentConfigRepository := repository.NewAssessmentConfigRepository(db)
	userapiClient := NewUserapiClient(configConfig)
	serviceUserapiClient := service.ProvideUserapiClient(userapiClient)
	assessmentConfigService := service.NewAssessmentConfigService(assessmentConfigRepository, serviceUserapiClient, integrationSecretRepository, v)
	assessmentConfigHandler := handler.NewAssessmentConfigHandler(assessmentConfigService)
	assessmentBatchRepository := repository.NewAssessmentBatchRepository(db)
	nowFunc := ProvideNowFunc()
	sessionFeatureRepository := repository.NewSessionFeatureRepository(db)
	evaluatorLLMClient := NewEvaluatorLLMClient(enabledModelProvider)
	dimensionSpecReaderAdapter := NewDimensionSpecReader(dimensionRepository)
	activityThresholdReader := NewActivityThresholdReader(dimensionRepository)
	dimensionScoreRepository := repository.NewDimensionScoreRepository(db)
	v2 := NewExtractorSysParamDefaults()
	systemParamReader := repository.NewSystemParamReader(db, v2)
	activityStatRepository := repository.NewActivityStatRepository(db)
	activity := NewActivityProvider(conversationlogClient, sessionFeatureRepository, activityThresholdReader, activityStatRepository, integrationSecretRepository, v)
	aggregateScoreRepository := repository.NewAggregateScoreRepository(db)
	scorerScorer := scorer.New(dimensionScoreRepository, aggregateScoreRepository)
	evaluator := NewEvaluatorProvider(evaluatorLLMClient, enabledModelProvider, sessionFeatureRepository, dimensionSpecReaderAdapter, activityThresholdReader, dimensionScoreRepository, systemParamReader, activity, scorerScorer)
	assessmentAlertRepository := repository.NewAssessmentAlertRepository(db)
	operationLogRepository := repository.NewOperationLogRepository(db)
	operationLogRecorder := service.NewOperationLogRecorder(operationLogRepository, accountRepository)
	alertWriter := NewAlertWriterAdapter(assessmentAlertRepository, operationLogRecorder)
	redisConnOpt := NewAsynqConnOpt(configConfig)
	asynqClient := asynq.NewClient(redisConnOpt)
	asynqEnqueuer := pipeline.NewAsynqEnqueuer(asynqClient)
	orchestrator := NewOrchestratorProvider(assessmentBatchRepository, sessionFeatureRepository, assessmentConfigRepository, conversationlogClient, userapiClient, integrationSecretRepository, v, evaluator, alertWriter, asynqEnqueuer, operationLogRecorder)
	assessmentBatchService := NewAssessmentBatchServiceAdapter(assessmentBatchRepository, assessmentConfigRepository, dimensionRepository, userapiClient, integrationSecretRepository, v, nowFunc, orchestrator)
	assessmentBatchHandler := handler.NewAssessmentBatchHandler(assessmentBatchService)
	assessmentTestTaskRepository := repository.NewAssessmentTestTaskRepository(db)
	questionRepository := repository.NewQuestionRepository(db)
	questionBatchRepository := repository.NewQuestionBatchRepository(db)
	asynqTestGradeEnqueuer := NewAsynqTestGradeEnqueuer(asynqClient)
	assessmentTestTaskService := NewAssessmentTestTaskServiceAdapter(assessmentTestTaskRepository, questionRepository, questionBatchRepository, dimensionRepository, userapiClient, integrationSecretRepository, v, nowFunc, asynqTestGradeEnqueuer)
	assessmentTestTaskHandler := handler.NewAssessmentTestTaskHandler(assessmentTestTaskService)
	assessmentTestAnswerRepository := repository.NewAssessmentTestAnswerRepository(db)
	answerService := NewAnswerServiceAdapter(assessmentTestAnswerRepository, assessmentTestTaskRepository, assessmentTestTaskService, questionRepository, dimensionRepository, nowFunc)
	answerHandler := handler.NewAnswerHandler(answerService)
	llmConfigService := service.NewLLMConfigService(llmConfigRepository, rsakeyManager, v)
	llmConfigHandler := handler.NewLLMConfigHandler(llmConfigService)
	integrationSecretService := service.NewIntegrationSecretService(integrationSecretRepository, rsakeyManager, v, conversationlogClient)
	integrationSecretHandler := handler.NewIntegrationSecretHandler(integrationSecretService)
	questionService := service.NewQuestionService(questionRepository, dimensionRepository, questionBatchRepository)
	questionBatchService := service.NewQuestionBatchService(questionBatchRepository, questionRepository, dimensionRepository)
	questionHandler := handler.NewQuestionHandler(questionService, questionBatchService)
	questionBatchHandler := handler.NewQuestionBatchHandler(questionBatchService)
	questionGenerationRepository := repository.NewQuestionGenerationRepository(db)
	asynqGenerationEnqueuer := NewAsynqGenerationEnqueuer(asynqClient)
	questionGenerationService := service.NewQuestionGenerationService(questionGenerationRepository, dimensionRepository, questionBatchRepository, asynqGenerationEnqueuer, enabledModelProvider)
	questionGenerationHandler := handler.NewQuestionGenerationHandler(questionGenerationService)
	scaleRepository := repository.NewScaleRepository(db)
	scaleService := service.NewScaleService(scaleRepository)
	scaleHandler := handler.NewScaleHandler(scaleService)
	assessmentTestResultRepository := repository.NewAssessmentTestResultRepository(db)
	profileService := service.NewProfileService(dimensionScoreRepository, aggregateScoreRepository, activityStatRepository, assessmentTestResultRepository, dimensionRepository, serviceUserapiClient, integrationSecretRepository, v)
	profileHandler := handler.NewProfileHandler(profileService)
	dashboardQueryRepository := repository.NewDashboardQueryRepository(db)
	teamTrainingSuggestionRepository := repository.NewTeamTrainingSuggestionRepository(db)
	dashboardService := service.NewDashboardService(dashboardQueryRepository, teamTrainingSuggestionRepository, dimensionRepository, assessmentTestResultRepository, serviceUserapiClient, integrationSecretRepository, v)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	workspaceQueryRepository := repository.NewWorkspaceQueryRepository(db)
	workspaceService := NewWorkspaceServiceAdapter(workspaceQueryRepository, dashboardQueryRepository, teamTrainingSuggestionRepository, dimensionRepository, assessmentConfigRepository, userapiClient, integrationSecretRepository, v, nowFunc)
	workspaceHandler := handler.NewWorkspaceHandler(workspaceService)
	engine := router.NewRouter(configConfig, manager, accountHandler, healthHandler, setupHandler, systemHandler, dimensionHandler, assessmentConfigHandler, assessmentBatchHandler, assessmentTestTaskHandler, answerHandler, llmConfigHandler, integrationSecretHandler, questionHandler, questionBatchHandler, questionGenerationHandler, scaleHandler, profileHandler, dashboardHandler, workspaceHandler, operationLogRecorder, client)
	httpAddr := NewHTTPAddr(configConfig)
	int2 := NewAsynqConcurrency(configConfig)
	asynqServer := server.NewServer(redisConnOpt, int2)
	extractorLLMClient := NewExtractorLLMClient(enabledModelProvider)
	extractor := NewExtractorProvider(extractorLLMClient, conversationlogClient, sessionFeatureRepository, systemParamReader, integrationSecretRepository, v)
	sessionExtractHandler := NewSessionExtractHandlerTyped(extractor)
	personEvaluateHandler := NewPersonEvaluateHandlerTyped(evaluator)
	batchTickHandler := NewBatchTickHandlerTyped(orchestrator)
	batchRunHandler := NewBatchRunHandlerTyped(orchestrator)
	questionGenLLMClient := NewQuestionGenLLMClient(enabledModelProvider)
	questionDimensionSpecReader := NewQuestionDimensionSpecReader(dimensionRepository)
	generator := NewQuestionGenProvider(questionGenLLMClient, questionGenerationRepository, questionDimensionSpecReader)
	questionGenerateHandler := NewQuestionGenerateHandlerTyped(generator)
	testExpireTickHandler := NewTestExpireTickHandlerTyped(assessmentTestTaskRepository, operationLogRecorder)
	gradingLLMClient := NewGradingLLMClient(enabledModelProvider)
	grader := NewGradingProvider(gradingLLMClient, enabledModelProvider, assessmentTestTaskRepository, questionRepository, assessmentTestAnswerRepository, assessmentTestResultRepository, dimensionRepository, dimensionScoreRepository, scorerScorer, assessmentConfigRepository, systemParamReader)
	testGradeHandler := NewTestGradeHandlerTyped(grader, assessmentTestTaskRepository, assessmentTestResultRepository)
	suggestGenLLMClient := NewSuggestGenLLMClient(enabledModelProvider)
	suggestgenGenerator := NewSuggestGenProvider(suggestGenLLMClient, enabledModelProvider, systemParamReader)
	asynqSuggestEnqueuer := NewAsynqSuggestEnqueuer(asynqClient)
	suggestService := NewSuggestServiceAdapter(teamTrainingSuggestionRepository, dashboardQueryRepository, assessmentBatchRepository, dimensionRepository, suggestgenGenerator, asynqSuggestEnqueuer, integrationSecretRepository, v, userapiClient, operationLogRecorder)
	suggestTickHandler := NewSuggestTickHandlerTyped(suggestService)
	suggestGenerateHandler := NewSuggestGenerateHandlerTyped(suggestService)
	operationLogCleanHandler := NewOperationLogCleanHandlerTyped(operationLogRecorder)
	serveMux := NewMuxAdapter(sessionExtractHandler, personEvaluateHandler, batchTickHandler, batchRunHandler, questionGenerateHandler, testExpireTickHandler, testGradeHandler, suggestTickHandler, suggestGenerateHandler, operationLogCleanHandler)
	asynqScheduler := scheduler.NewScheduler(redisConnOpt)
	app := &App{
		Config:      configConfig,
		Engine:      engine,
		HTTPAddr:    httpAddr,
		DB:          db,
		Redis:       client,
		AsynqClient: asynqClient,
		AsynqServer: asynqServer,
		Mux:         serveMux,
		Scheduler:   asynqScheduler,
		Recorder:    operationLogRecorder,
	}
	return app, nil
}
