/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AnswerTokenRouteImport } from './routes/answer/$token'
import { Route as AuthenticatedSystemParamsRouteImport } from './routes/_authenticated/system/params'
import { Route as AuthenticatedSystemStatusRouteImport } from './routes/_authenticated/system/status'
import { Route as AuthenticatedSystemDimensionIndexRouteImport } from './routes/_authenticated/system/dimension/index'
import { Route as AuthenticatedSystemLlmIndexRouteImport } from './routes/_authenticated/system/llm/index'
import { Route as AuthenticatedSystemUsersIndexRouteImport } from './routes/_authenticated/system/users/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnswerTokenRoute = AnswerTokenRouteImport.update({
  id: '/answer/$token',
  path: '/answer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemParamsRoute =
  AuthenticatedSystemParamsRouteImport.update({
    id: '/system/params',
    path: '/system/params',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemStatusRoute =
  AuthenticatedSystemStatusRouteImport.update({
    id: '/system/status',
    path: '/system/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDimensionIndexRoute =
  AuthenticatedSystemDimensionIndexRouteImport.update({
    id: '/system/dimension/',
    path: '/system/dimension/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemLlmIndexRoute =
  AuthenticatedSystemLlmIndexRouteImport.update({
    id: '/system/llm/',
    path: '/system/llm/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersIndexRoute =
  AuthenticatedSystemUsersIndexRouteImport.update({
    id: '/system/users/',
    path: '/system/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/answer/$token': typeof AnswerTokenRoute
  '/system/params': typeof AuthenticatedSystemParamsRoute
  '/system/status': typeof AuthenticatedSystemStatusRoute
  '/system/dimension/': typeof AuthenticatedSystemDimensionIndexRoute
  '/system/llm/': typeof AuthenticatedSystemLlmIndexRoute
  '/system/users/': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/answer/$token': typeof AnswerTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/system/params': typeof AuthenticatedSystemParamsRoute
  '/system/status': typeof AuthenticatedSystemStatusRoute
  '/system/dimension': typeof AuthenticatedSystemDimensionIndexRoute
  '/system/llm': typeof AuthenticatedSystemLlmIndexRoute
  '/system/users': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/answer/$token': typeof AnswerTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/system/params': typeof AuthenticatedSystemParamsRoute
  '/_authenticated/system/status': typeof AuthenticatedSystemStatusRoute
  '/_authenticated/system/dimension/': typeof AuthenticatedSystemDimensionIndexRoute
  '/_authenticated/system/llm/': typeof AuthenticatedSystemLlmIndexRoute
  '/_authenticated/system/users/': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/answer/$token'
    | '/system/params'
    | '/system/status'
    | '/system/dimension/'
    | '/system/llm/'
    | '/system/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/answer/$token'
    | '/'
    | '/system/params'
    | '/system/status'
    | '/system/dimension'
    | '/system/llm'
    | '/system/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/answer/$token'
    | '/_authenticated/'
    | '/_authenticated/system/params'
    | '/_authenticated/system/status'
    | '/_authenticated/system/dimension/'
    | '/_authenticated/system/llm/'
    | '/_authenticated/system/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  AnswerTokenRoute: typeof AnswerTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/answer/$token': {
      id: '/answer/$token'
      path: '/answer/$token'
      fullPath: '/answer/$token'
      preLoaderRoute: typeof AnswerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system/params': {
      id: '/_authenticated/system/params'
      path: '/system/params'
      fullPath: '/system/params'
      preLoaderRoute: typeof AuthenticatedSystemParamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/status': {
      id: '/_authenticated/system/status'
      path: '/system/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof AuthenticatedSystemStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/dimension/': {
      id: '/_authenticated/system/dimension/'
      path: '/system/dimension'
      fullPath: '/system/dimension/'
      preLoaderRoute: typeof AuthenticatedSystemDimensionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/llm/': {
      id: '/_authenticated/system/llm/'
      path: '/system/llm'
      fullPath: '/system/llm/'
      preLoaderRoute: typeof AuthenticatedSystemLlmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/': {
      id: '/_authenticated/system/users/'
      path: '/system/users'
      fullPath: '/system/users/'
      preLoaderRoute: typeof AuthenticatedSystemUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSystemParamsRoute: typeof AuthenticatedSystemParamsRoute
  AuthenticatedSystemStatusRoute: typeof AuthenticatedSystemStatusRoute
  AuthenticatedSystemDimensionIndexRoute: typeof AuthenticatedSystemDimensionIndexRoute
  AuthenticatedSystemLlmIndexRoute: typeof AuthenticatedSystemLlmIndexRoute
  AuthenticatedSystemUsersIndexRoute: typeof AuthenticatedSystemUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSystemParamsRoute: AuthenticatedSystemParamsRoute,
  AuthenticatedSystemStatusRoute: AuthenticatedSystemStatusRoute,
  AuthenticatedSystemDimensionIndexRoute:
    AuthenticatedSystemDimensionIndexRoute,
  AuthenticatedSystemLlmIndexRoute: AuthenticatedSystemLlmIndexRoute,
  AuthenticatedSystemUsersIndexRoute: AuthenticatedSystemUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  AnswerTokenRoute: AnswerTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
