feature_id: P2_WRK_001_FEAT_工作台
module_code: WRK
phase: P2
type: FEAT
root_base: null
base_on: null
change_group: null
change_history: []
dependencies:
- P2_ASM_001_FEAT_周期批量评估跑批编排
- P2_TST_001_FEAT_主动测试评估运营
- P2_PRF_001_FEAT_个人画像
- P2_TMD_001_FEAT_团队看板
- P1_ACC_001_FEAT_登录与用户管理
feature_name: 工作台
creator: lixuetao
created_at: '2026-10-06T04:37:52Z'
updated_at: '2026-10-06T13:50:10Z'
stages:
  specs:
    status: completed
    started_at: '2026-10-06T07:52:58Z'
    completed_at: '2026-10-06T07:52:58Z'
    check_owner: lixuetao
  interface:
    status: completed
    started_at: '2026-10-06T07:52:58Z'
    completed_at: '2026-10-06T11:10:08Z'
    check_owner: lixuetao
  dev_plan:
    status: completed
    started_at: '2026-10-06T11:10:08Z'
    completed_at: '2026-10-06T13:50:10Z'
    check_owner: lixuetao
  dev_exec:
    status: in_progress
    started_at: '2026-10-06T13:50:10Z'
    completed_at: null
    check_owner: null
rollback_history:
- timestamp: '2026-10-06T05:50:10Z'
  type: dependencies
  from_stage: specs
  to_stage: null
  reason: null
  check_owner: lixuetao
  affected_stages: []
- timestamp: '2026-10-06T06:28:42Z'
  type: dependencies
  from_stage: specs
  to_stage: null
  reason: null
  check_owner: lixuetao
  affected_stages: []
- timestamp: '2026-10-06T07:52:58Z'
  type: advance
  from_stage: specs
  to_stage: specs
  reason: null
  check_owner: lixuetao
  affected_stages:
  - specs
  - interface
- timestamp: '2026-10-06T11:10:08Z'
  type: advance
  from_stage: interface
  to_stage: interface
  reason: null
  check_owner: lixuetao
  affected_stages:
  - interface
  - dev_plan
- timestamp: '2026-10-06T13:50:10Z'
  type: advance
  from_stage: dev_plan
  to_stage: dev_plan
  reason: null
  check_owner: lixuetao
  affected_stages:
  - dev_plan
  - dev_exec
